name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Substitua pela versão do Python que você utiliza

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build the package
      run: python -m build

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__  # O nome de usuário deve ser sempre "__token__" ao usar o token de API
        TWINE_PASSWORD: ${{ secrets.PYPITOKEN }}  # O token de API do PyPI armazenado como secret no GitHub
      run: |
        pip install twine
        twine upload dist/*
